replicaCount: 2
nginxVersion: "1.21.6"
serviceAccount:
  create: true
ingress:
  enabled: false
  host: "example.com"
service:
  type: ClusterIP
  name: my-service
  port: 80
autoscaling:
  enabled: false
  target:
    name: my-deployment
  minReplicas: 1
  maxReplicas: 5
  cpuTargetPercentage: 80
