{{- if .Values.ingress.enabled | default false }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default "example.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name | default "my-service" }}
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end }}
