apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.tag }}"
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
