apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
  - name: beats-port       # Nome para a porta de entrada do Logstash
    protocol: TCP
    port: 5044
    targetPort: 5044
  - name: http-monitoring  # Nome para a porta de monitoramento do Logstash
    protocol: TCP
    port: 9600
    targetPort: 9600
  type: {{ .Values.serviceType }}
