apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  - protocol: TCP
    port: 9600
    targetPort: 9600
  type: {{ .Values.serviceType }}
